"""Academic prototype risk scoring algorithm for static Android analysis.

Calculates a transparent, explainable risk score (0-100) based on documented
severity base weights and confidence multipliers.

IMPORTANT DISCLAIMER:
This risk score is a heuristic prioritisation metric developed for this research prototype
and should not be interpreted as CVSS or proof of exploitation.
"""

from __future__ import annotations

import logging
from typing import Any, Sequence

from data_leak_detector.core.models import (
    Confidence,
    FindingCategory,
    PermissionFinding,
    RiskRating,
    RiskScore,
    RiskScoreResult,
    SecurityFinding,
    Severity,
)


logger = logging.getLogger(__name__)

PROTOTYPE_DISCLAIMER: str = (
    "This risk score is a heuristic prioritisation metric developed for this research prototype "
    "and should not be interpreted as CVSS or proof of exploitation."
)


class RiskScorer:
    """Transparent academic prototype risk scorer for static analysis findings.
    
    Guarantees:
    - Explainability: Maintains an itemized audit trail of how every point was computed.
    - Low-severity mitigation: Caps the aggregate contribution of low-severity findings.
    - Repetition mitigation: Applies diminishing returns to multiple occurrences of the same rule.
    - Category caps: Prevents any single finding category from monopolizing the score.
    - Normalization: Bounds final score strictly between 0.0 and 100.0.
    """

    # Severity base weights
    SEVERITY_WEIGHTS: dict[Severity, float] = {
        Severity.CRITICAL: 25.0,
        Severity.HIGH: 15.0,
        Severity.MEDIUM: 8.0,
        Severity.LOW: 3.0,
        Severity.INFO: 0.0,
    }

    # Confidence multipliers
    CONFIDENCE_MULTIPLIERS: dict[Confidence, float] = {
        Confidence.HIGH: 1.0,
        Confidence.MEDIUM: 0.75,
        Confidence.LOW: 0.5,
    }

    # Multipliers for repeated findings generated by the same rule (diminishing returns)
    REPETITION_DECAY: tuple[float, ...] = (1.0, 0.5, 0.25)

    # Maximum score contribution from all Low-severity findings combined
    LOW_SEVERITY_TOTAL_CAP: float = 15.0

    # Maximum score contribution from any single finding category
    CATEGORY_CAP: float = 35.0

    # Maximum score contribution from any single rule
    PER_RULE_CAP: float = 25.0

    def __init__(
        self,
        severity_weights: dict[Severity, float] | None = None,
        confidence_multipliers: dict[Confidence, float] | None = None,
        category_cap: float | None = None,
        low_severity_cap: float | None = None,
    ) -> None:
        self.weights = severity_weights or dict(self.SEVERITY_WEIGHTS)
        self.multipliers = confidence_multipliers or dict(self.CONFIDENCE_MULTIPLIERS)
        self.category_cap = category_cap if category_cap is not None else self.CATEGORY_CAP
        self.low_severity_cap = low_severity_cap if low_severity_cap is not None else self.LOW_SEVERITY_TOTAL_CAP

    @classmethod
    def get_rating_band(cls, score: float) -> RiskRating:
        """Map normalized numeric score (0-100) to qualitative rating band:
        - 0-19: Minimal
        - 20-39: Low
        - 40-59: Medium
        - 60-79: High
        - 80-100: Critical
        """
        bounded = min(100.0, max(0.0, score))
        if bounded >= 80.0:
            return RiskRating.CRITICAL
        elif bounded >= 60.0:
            return RiskRating.HIGH
        elif bounded >= 40.0:
            return RiskRating.MEDIUM
        elif bounded >= 20.0:
            return RiskRating.LOW
        else:
            return RiskRating.MINIMAL

    @classmethod
    def calculate_score(
        cls,
        findings_or_permissions: Sequence[Any] | None = None,
        findings: Sequence[SecurityFinding] | None = None,
        permissions: Sequence[PermissionFinding] | None = None,
    ) -> RiskScore:
        """Class method calculating risk score. Accommodates various argument orders."""
        scorer = cls()
        return scorer.calculate(
            findings_or_permissions=findings_or_permissions,
            findings=findings,
            permissions=permissions,
        )

    def calculate(
        self,
        findings_or_permissions: Sequence[Any] | None = None,
        findings: Sequence[SecurityFinding] | None = None,
        permissions: Sequence[PermissionFinding] | None = None,
    ) -> RiskScore:
        """Calculate normalized, explainable risk score from findings.
        
        Args:
            findings_or_permissions: Findings list (or permissions if passed first).
            findings: Explicit findings sequence keyword argument.
            permissions: Optional permission findings sequence.
            
        Returns:
            RiskScore dataclass containing score, rating, disclaimer, and audit trail.
        """
        # Resolve polymorphic parameter passing
        target_findings: list[SecurityFinding] = []
        if findings is not None:
            target_findings = list(findings)
        elif findings_or_permissions is not None:
            # Check if first arg is findings or permissions
            first_items = list(findings_or_permissions)
            if first_items and isinstance(first_items[0], PermissionFinding):
                # First arg was permissions, second may be findings
                pass
            else:
                target_findings = [f for f in first_items if isinstance(f, SecurityFinding)]

        explanations: list[str] = [PROTOTYPE_DISCLAIMER]

        if not target_findings:
            explanations.append("No security findings were detected; assigned baseline score of 0.0 (Minimal risk).")
            return RiskScore(
                score=0.0,
                rating=RiskRating.MINIMAL,
                summary="No security findings detected. Overall risk is Minimal.",
                disclaimer=PROTOTYPE_DISCLAIMER,
                breakdown={"findings": []},
                category_scores={},
                findings_evaluated=0,
                findings_deduplicated=0,
                rule_contributions={},
                explanations=explanations,
            )

        # -------------------------------------------------------------------
        # Step 1: Deduplication of exact findings
        # -------------------------------------------------------------------
        seen_keys: set[tuple[str, str, str, str]] = set()
        unique_findings: list[SecurityFinding] = []
        deduplicated_count = 0

        for f in target_findings:
            key = (
                f.rule_id,
                f.title,
                str(f.evidence).strip(),
                str(f.location).strip() if f.location else "",
            )
            if key in seen_keys:
                deduplicated_count += 1
                continue
            seen_keys.add(key)
            unique_findings.append(f)

        if deduplicated_count > 0:
            explanations.append(
                f"Deduplication: Filtered {deduplicated_count} exact duplicate finding(s) out of {len(target_findings)} total."
            )

        # -------------------------------------------------------------------
        # Step 2: Calculate finding raw scores & rule diminishing returns
        # -------------------------------------------------------------------
        rule_occurrence_counts: dict[str, int] = {}
        rule_raw_contributions: dict[str, float] = {}
        category_raw_scores: dict[str, list[tuple[float, Severity, dict[str, Any]]]] = {}
        itemized_breakdown: list[dict[str, Any]] = []

        for f in unique_findings:
            sev = f.severity if isinstance(f.severity, Severity) else Severity(f.severity)
            conf = f.confidence if isinstance(f.confidence, Confidence) else Confidence(f.confidence)

            base_w = self.weights.get(sev, 0.0)
            conf_m = self.multipliers.get(conf, 1.0)
            single_raw = base_w * conf_m

            # Apply repetition decay for multiple distinct occurrences of the same rule_id
            rule_id = f.rule_id
            occ_index = rule_occurrence_counts.get(rule_id, 0)
            rule_occurrence_counts[rule_id] = occ_index + 1

            decay_multiplier = (
                self.REPETITION_DECAY[occ_index]
                if occ_index < len(self.REPETITION_DECAY)
                else 0.0
            )

            current_rule_total = rule_raw_contributions.get(rule_id, 0.0)
            potential_addition = single_raw * decay_multiplier

            # Enforce per-rule cap
            if current_rule_total + potential_addition > self.PER_RULE_CAP:
                actual_addition = max(0.0, self.PER_RULE_CAP - current_rule_total)
            else:
                actual_addition = potential_addition

            rule_raw_contributions[rule_id] = current_rule_total + actual_addition

            finding_detail = {
                "rule_id": f.rule_id,
                "title": f.title,
                "severity": sev.value,
                "confidence": conf.value,
                "base_weight": base_w,
                "confidence_multiplier": conf_m,
                "occurrence_index": occ_index + 1,
                "decay_factor": decay_multiplier,
                "raw_calculated": single_raw,
                "adjusted_score": actual_addition,
                "category": f.category.value if hasattr(f.category, "value") else str(f.category),
            }
            itemized_breakdown.append(finding_detail)

            cat_name = f.category.value if hasattr(f.category, "value") else str(f.category)
            category_raw_scores.setdefault(cat_name, []).append((actual_addition, sev, finding_detail))

        # -------------------------------------------------------------------
        # Step 3: Low-severity aggregate cap and category caps
        # -------------------------------------------------------------------
        # Enforce global low severity cap
        total_low_points = sum(
            item["adjusted_score"]
            for item in itemized_breakdown
            if item["severity"] == Severity.LOW.value
        )
        low_cap_applied = False
        if total_low_points > self.low_severity_cap:
            low_cap_applied = True
            low_scale_factor = self.low_severity_cap / total_low_points
            for item in itemized_breakdown:
                if item["severity"] == Severity.LOW.value:
                    item["adjusted_score"] = round(item["adjusted_score"] * low_scale_factor, 2)
            explanations.append(
                f"Low-Severity Cap: Combined Low-severity findings ({total_low_points:.1f} pts) "
                f"capped at maximum {self.low_severity_cap:.1f} pts to prevent inflation."
            )

        # Enforce category caps
        category_final_scores: dict[str, float] = {}
        for cat_name, cat_items in category_raw_scores.items():
            cat_sum = sum(
                item["adjusted_score"]
                for item in itemized_breakdown
                if item["category"] == cat_name
            )
            if cat_sum > self.category_cap:
                category_final_scores[cat_name] = self.category_cap
                explanations.append(
                    f"Category Cap: Category '{cat_name}' sum ({cat_sum:.1f} pts) capped at {self.category_cap:.1f} pts."
                )
            else:
                category_final_scores[cat_name] = round(cat_sum, 2)

        # -------------------------------------------------------------------
        # Step 4: Normalization and Rating Band
        # -------------------------------------------------------------------
        total_raw_score = sum(category_final_scores.values())
        final_normalized_score = min(100.0, max(0.0, round(total_raw_score, 1)))
        rating = self.get_rating_band(final_normalized_score)

        explanations.append(
            f"Final Aggregation: Category subtotals sum to {total_raw_score:.1f} pts; "
            f"normalized score is {final_normalized_score:.1f} / 100.0 (Rating: {rating.value})."
        )

        summary_text = (
            f"Overall static risk score is {final_normalized_score:.1f}/100 ({rating.value}). "
            f"Evaluated {len(target_findings)} findings across {len(category_final_scores)} categories. "
            f"{PROTOTYPE_DISCLAIMER}"
        )

        return RiskScore(
            score=final_normalized_score,
            rating=rating,
            summary=summary_text,
            disclaimer=PROTOTYPE_DISCLAIMER,
            breakdown={"findings": itemized_breakdown},
            category_scores=category_final_scores,
            findings_evaluated=len(target_findings),
            findings_deduplicated=deduplicated_count,
            rule_contributions={r: round(c, 2) for r, c in rule_raw_contributions.items()},
            explanations=explanations,
        )
