"""Abstract base class and contract for all static analysis detection rules."""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from typing import Any

from data_leak_detector.core.models import (
    Confidence,
    Finding,
    FindingCategory,
    SecurityFinding,
    Severity,
)


logger = logging.getLogger(__name__)


class BaseRule(ABC):
    """Abstract static analysis rule interface.
    
    Every rule must define:
    - rule_id: Unique string identifier (e.g. 'SEC-001')
    - title: Human-readable vulnerability or indicator title
    - category: FindingCategory enum or category string
    - default_severity: Baseline severity level (Severity enum)
    - description: Comprehensive description of the static check
    - owasp_reference: OWASP Mobile Top 10 or MASVS reference if applicable
    """

    rule_id: str
    title: str
    category: FindingCategory | str
    default_severity: Severity
    description: str
    owasp_reference: str | None = None
    enabled: bool = True

    @property
    def severity(self) -> Severity:
        """Backwards-compatible alias for default_severity."""
        return self.default_severity

    @abstractmethod
    def evaluate(self, context: dict[str, Any] | Any) -> list[SecurityFinding]:
        """Evaluate static indicators from parsed APK context.
        
        Args:
            context: Extracted manifest, string pools, method invocations, or ParsedAPKData.
            
        Returns:
            List of SecurityFinding objects generated by this rule.
        """

    def create_finding(
        self,
        description: str,
        evidence: str,
        location: str | None = None,
        severity: Severity | None = None,
        confidence: Confidence = Confidence.HIGH,
        impact: str | None = None,
        remediation: str | None = None,
        title: str | None = None,
        owasp_reference: str | None = None,
    ) -> SecurityFinding:
        """Helper to create a validated SecurityFinding initialized with rule defaults."""
        return SecurityFinding(
            rule_id=self.rule_id,
            title=title or self.title,
            category=self.category,
            severity=severity or self.default_severity,
            confidence=confidence,
            description=description or self.description,
            evidence=evidence,
            location=location,
            impact=impact,
            remediation=remediation,
            owasp_reference=owasp_reference or self.owasp_reference,
            is_static_indicator=True,
        )
